# Generated by Django 4.1.2 on 2022-10-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leasingapp', '0002_registerlesse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registerlesse',
            new_name='register',
        ),
    ]
