# Generated by Django 4.1.2 on 2022-10-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leasingapp', '0004_alter_register_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesseereg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Username', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=70)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='lessorreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Username', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=70)),
            ],
        ),
        migrations.RenameField(
            model_name='uploadfile',
            old_name='static',
            new_name='Image',
        ),
        migrations.AlterField(
            model_name='register',
            name='Address',
            field=models.CharField(max_length=70),
        ),
    ]
