# Generated by Django 4.1.2 on 2022-10-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leasingapp', '0005_lesseereg_lessorreg_rename_static_uploadfile_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lesseereg',
            new_name='reglessee',
        ),
    ]
