# Generated by Django 4.1.2 on 2022-10-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leasingapp', '0006_rename_lesseereg_reglessee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reglessee',
            new_name='lesseereg',
        ),
    ]
