# Generated by Django 4.1.2 on 2022-10-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leasingapp', '0007_rename_reglessee_lesseereg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lessorreg',
            new_name='lessor',
        ),
    ]
