# Generated by Django 4.1.2 on 2022-10-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leasingapp', '0009_rename_lesseereg_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lessor',
            new_name='adder',
        ),
    ]
