# Generated by Django 4.1.2 on 2022-10-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leasingapp', '0011_delete_adder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='Image',
            new_name='Picture',
        ),
    ]
