# Generated by Django 4.1.2 on 2022-10-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leasingapp', '0012_rename_image_uploadfile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
