# Generated by Django 4.1.2 on 2022-10-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leasingapp', '0013_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='adder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Username', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=70)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
