# Generated by Django 4.1.2 on 2022-10-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leasingapp', '0016_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adder',
            name='Name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='adder',
            name='Username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='Name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='Description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='Name',
            field=models.CharField(max_length=85),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(max_length=50),
        ),
    ]
